### ISSUE TITLE
missing days from heatmaps? #notAnIsuue

### ISSUE THREAD

**Issue by Richardsl** [corinnekaryiu/obsidian-habit-mood-tracker#1]
Hi
I see that the days are missing from the heatmap (tue, thu, sat).
Is this something you removed yourself or is this a bug in heatmap?

best regards, Richard (heatmap plugin creator)

**Comment by corinnekaryiu** [comment]
Hey @Richardsl! Thanks so much for the brilliant plugin.

I removed the day column via CSS for a cleaner look for my own use (as seen in the screenshot) but it is shown by default.
