### ISSUE TITLE
stopped working with recent updates

### ISSUE THREAD

**Issue by barnabaslabs** [corinnekaryiu/obsidian-habit-mood-tracker#3]
Hi, 
I have been using your code happily for several weeks, but it sadly has stopped working. The screenshot will show you what I mean. Most of the squares in June were filled in for each of the sections. I know that the heatmaps plugin just updated and it stopped working then. Is it still working for you?
Thanks,
Jack
![image](https://user-images.githubusercontent.com/121033/176083677-a9e1d005-82ef-416c-b55d-07accfdf4cde.png)

**Comment by corinnekaryiu** [comment]
Hey @pastorjack, thanks for flagging!

I just got back from a long holiday and noticed the same thing. Will look into the Heatmap plugin code updates for a fix! 🤞🏻

**Comment by corinnekaryiu** [comment]
@pastorjack Looks like a couple of settings were added to the Heatmaps plugin relating to colour intensity. They're supposed to be optional, but none of my colours show up unless I add the code myself.

You should be able to fix the issue by adding something like this into your code, just before `entries: []`:

```
	intensityScaleStart: 1,
	intensityScaleEnd: 5,
```

I only use intensity level 5 so the above works for me - you may need to experiment with your own setup!

**Comment by barnabaslabs** [comment]
That worked! Thank you so much!
![SmartSelect_20220628-084655_Obsidian](https://user-images.githubusercontent.com/121033/176223771-0007e30f-ec66-425b-8bb9-a07cf1ee0bd9.jpg)
